version: '3'

services:
  chatsapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatsapp
    depends_on:
      - "db"
    ports:
    - '9000:9000'
    command: ["/go/src/chatsapp/scripts/wait-for-it.sh", "db:3306", "--", "/go/src/chatsapp/bin/chatsapp"]

  db:
    image: mysql:8.0.21
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'
#      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: chatsapp

#volumes:
#  dbdata:
#    driver: local